language: node_js
node_js:
  - 6.10.1
services:
  - postgresql
before_install:
  - npm install sequelize-cli -g
before_script:
  - psql -c 'create database "doc-manager-test";' -U postgres  && sequelize db:migrate 

script: "npm run test:coverage"

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
